import { Language, Parser, type Tree } from "web-tree-sitter";
import { bashWasmBase64, runtimeWasmBase64 } from "../../vendor/wasm.gen.ts";

// The wasm is embedded as base64 (generated by `deno task embed:wasm`) so it
// rides along in the module graph. Resolving it from the npm dependencies at
// runtime is not viable: when the package runs from JSR, import.meta.resolve
// yields an npm: URL that neither fetch nor Deno.readFile can read.
function decodeWasm(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

let parserPromise: Promise<Parser> | null = null;

function getParser(): Promise<Parser> {
  if (!parserPromise) {
    parserPromise = (async () => {
      await Parser.init({ wasmBinary: decodeWasm(runtimeWasmBase64) });
      const bash = await Language.load(decodeWasm(bashWasmBase64));
      const parser = new Parser();
      parser.setLanguage(bash);
      return parser;
    })();
  }
  return parserPromise;
}

export async function parse(source: string): Promise<Tree | null> {
  const parser = await getParser();
  return parser.parse(source);
}
