function encodeBase64(bytes: Uint8Array): string {
  // Chunked to stay clear of the argument-count limit on String.fromCharCode.
  let binary = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}

// web-tree-sitter exports its runtime wasm as a subpath; tree-sitter-bash ships
// the prebuilt grammar wasm at its package root. Read them from the npm cache and
// emit a TS module so the bytes ride along in our published module graph. That
// lets the package run from JSR without resolving npm: URLs (which fetch cannot
// read) or hitting the network at runtime.
const runtime = await Deno.readFile(
  new URL(import.meta.resolve("web-tree-sitter/web-tree-sitter.wasm")),
);
const grammar = await Deno.readFile(
  new URL(import.meta.resolve("tree-sitter-bash/tree-sitter-bash.wasm")),
);

const out = new URL("../vendor/wasm.gen.ts", import.meta.url);
await Deno.mkdir(new URL("../vendor/", import.meta.url), { recursive: true });
const contents = `// @generated by scripts/embed-wasm.ts — do not edit by hand.
// Tree-sitter wasm embedded as base64 so the package runs from JSR without
// resolving npm: URLs or fetching over the network. Regenerate with
// \`deno task embed:wasm\` after bumping web-tree-sitter or tree-sitter-bash.
export const runtimeWasmBase64 = "${encodeBase64(runtime)}";
export const bashWasmBase64 = "${encodeBase64(grammar)}";
`;

await Deno.writeTextFile(out, contents);
console.log(
  `wrote ${out.pathname} (runtime ${runtime.length}B, grammar ${grammar.length}B)`,
);
